### PR TITLE
Fix: Truncate shouldn't throw on invalid input

### LINKED ISSUE #86: Truncate is unsafe
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
`truncate` doesn't check that it's operating on a string and will throw if a non error object is logged to `err`.

## Steps to Reproduce
```javascript
logger.error({ err: { "not-object": true } }); // This will throw in this library's truncate function
```

## Expected Behavior

```javascript
logger.error({ err: { "not-object": true } }); // This should not throw
```
## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

### PR DESCRIPTION
**Pull request by jmealo**
## Proposed Release Notes
 * Fixed an issue where logging non-standard error objects under the `err` key causes APM to throw.

## Links
Fixes #86 

## Details
This fixes the reported issue.

### CODE REVIEW

**Review by bizob2828 — DISMISSED** [review]
thanks for these fixes @jmealo!  We fixed this in [our agent](https://github.com/newrelic/node-newrelic/blob/main/lib/util/application-logging.js#L19) but I guess it never made it to the deprecated log enrichers

**Review by bizob2828 — DISMISSED** [review]

**Comment by jmealo** [comment]
@bizob2828: No problem! Thanks for the quick review. I signed the CLA but it looks like it's still in the yellow status for the CI check.

**Comment by jmealo** [comment]
Not sure if it's related to this:
https://github.com/cla-assistant/cla-assistant/issues/211

**Comment by bizob2828** [comment]
@jmealo it's me I think. I pushed tests and CLA assistant isn't properly validating New Relic employees at the moment.

**Comment by jmealo** [comment]
@bizob2828: try now? :)

**Comment by bizob2828** [comment]
@jmealo it's not you. I will take care of it.

**Review by bizob2828 — APPROVED** [review]

**Comment by bizob2828** [comment]
@jmealo not sure which library you need but they have been released as `@newrelic/pino-enricher@1.1.1` or `@newrelic/winston-enricher@4.0.1`

**Pull request merged**
